### ISSUE TITLE
Feature Request: Docker image

### ISSUE THREAD

**Issue by JesseWebDotCom** [eleonne/synology-tagger#1]
This sounds pretty cool but I fear the setup is too much for most people. Would you be able to creat a docker image for this?  Thanks in advance

**Comment by eleonne** [comment]
Not a bad idea. I`ll create an image to simplify the process. Part of it will still be manual as there is no way to circumvent the database user part.

**Comment by eleonne** [comment]
So, I did the thing. Not just the docker, but a web interface with all sorts of configs, automations, real-time update, scheduling...you name it.

Still have to figure how to publish on docker hub and trying to squeeze it a little (its 20gb right now), but its finished.

**Comment by eleonne** [comment]
![image](https://github.com/eleonne/synology-tagger/assets/4657162/a88387b2-7b2c-4b1f-ba46-a9bbd1fa33ad)
![image](https://github.com/eleonne/synology-tagger/assets/4657162/e95cd22d-6bbe-47f6-b2f4-811b3276cff2)

**Comment by JesseWebDotCom** [comment]
That looks awesome!

**Comment by eleonne** [comment]
Docs updated, code commited, image uploaded to docker hub.

All is good. Closing the issue.
