### ISSUE TITLE
[Docs]: Please add description on how to get the Postgres credentials from NAS

### ISSUE THREAD

**Issue by ppetruneac** [eleonne/synology-tagger#2]
Hi @eleonne - Thank you very much for your work here. Very useful from what I can see. 

Can you please update docs in terms of how to get the Postgres credentials and connexion to the Synology NAS? Thank you 

> I am planning to test this out on my end and maybe help with the translation etc. And I think there is more scope to this too. For instance, Synology makes is really hard to update location - actually not possible at all (videos do not have a UI location field) but maybe this can be updated on the back end with an extension like this tool you built with different UI. We can use Google Maps API / geolocation to search for a location and then assign it. Or maybe there is an ML model to predict the location but this is more prone to error. 

I am looking forward to  hearing from you.

**Comment by eleonne** [comment]
So, that already exists. I have two branches in this project (1.0 and 2.0). You will find details on how to connect to postgres in the 1.0's readme. You can also take a look into [/scripts/enable_postgres_connection.sh](https://github.com/eleonne/synology-tagger/blob/2.0/scripts/enable_postgres_connection.sh)

In short:
1. Enable SSH and connect to your NAS
2. sudo echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/pg_hba.conf
3. sudo echo "listen_addresses = '*'" >> /etc/postgresql/postgresql.conf
4. psql -d synofoto
5. CREATE ROLE <username> WITH LOGIN SUPERUSER PASSWORD '<password>';

As always, be careful when doing these changes. Its possible to break your synology Photos.

And remember, this is not an official support from Synology, so use it at your own risk.
